import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/app-sidebar';
import { ThemeToggle } from '@/components/theme-toggle';
import { Button } from '@/components/ui/button';
import { IconBrandGithub, IconBrandLinkedin } from '@tabler/icons-react';
import { DeviceToggleGroup } from '@/components/device-toggle-group';
import { DeviceProvider } from '@/app/providers/device-context';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          // enableSystem
          disableTransitionOnChange
        >
          <DeviceProvider>
            <SidebarProvider>
              <AppSidebar />
              <SidebarInset>
                <main className="bg-zinc-100 dark:bg-black w-full h-full rounded-xl overflow-clip flex flex-col max-h-[calc(100vh-1rem)] not-md:max-h-screen">
                  <header className="flex justify-between p-4 border-b border-zinc-200 dark:border-zinc-800">
                    <SidebarTrigger />
                    <DeviceToggleGroup />
                    <div className="space-x-2">
                      <Button
                        size="icon"
                        variant="outline"
                        className="sm:size-7"
                      >
                        <IconBrandGithub
                          size={20}
                          className="text-foreground"
                        />
                      </Button>
                      <Button
                        size="icon"
                        variant="outline"
                        className="sm:size-7"
                      >
                        <IconBrandLinkedin
                          size={20}
                          className="text-foreground"
                        />
                      </Button>
                      <ThemeToggle />
                    </div>
                  </header>
                  <div className="flex-1 overflow-y-auto min-h-0">
                    {children}
                  </div>
                </main>
              </SidebarInset>
            </SidebarProvider>
          </DeviceProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
